es_host: localhost
es_port: 9200
writeback_index: elastalert
run_every:
  minutes: 2
buffer_time:
  minutes: 1
rules_folder: examples
rules_loader: "punch_plugins.rules_loader.my_use_case.complex_rule_loader.ComplexRuleLoader"
mongo_url: test.com
mongo_db: testdb